apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp
        image: jagratimishra1415/blue-green-deploy:latest
        env:
        - name: COLOR
          value: "BLUE"
        ports:
        - containerPort: 5000
