name: Blue-Green Deployment
on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t jagratimishra1415/blue-green-deploy:latest ./blue-green-app/app
        docker push jagratimishra1415/blue-green-deploy:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3


    
